### ISSUE TITLE
Parsing error: Cannot read properties of null (reading 'type')

### ISSUE THREAD

**Issue by Techn1x** [NullVoxPopuli/ember-eslint-parser#30]
In a GTS file

```ts
const [, ...createdClasses] = await Promise.all([minimumDuration, ...savePromises])
```
results in
`Parsing error: Cannot read properties of null (reading 'type')`

This worked fine under the existing setup prior to eslint-plugin-ember v12

If you define the first variable, eslint will stop complaining (though may start complaining about unused var, but at least that rule can be ignored)
```ts
const [_ignore, ...createdClasses] = await Promise.all([minimumDuration, ...savePromises])
```

**Comment by NullVoxPopuli** [comment]
Thanks for the insue report!

Any chance you'd be willing to add an example file to the test set of files in a failing pr?

**Comment by Techn1x** [comment]
Oh! I should also mention, the error went away if the `<template></template>` is removed from the file. File needs to have both the `const [, ...createdClasses]` and the template tags in order to produce the error.

I'll try to find some time to get that failing test done

**Comment by Techn1x** [comment]
all done, easier that I thought it would be to replicate 👍

**Comment by patricklx** [comment]
fixed by https://github.com/NullVoxPopuli/ember-eslint-parser/pull/33

**Comment by Techn1x** [comment]
Can confirm this works now in my project. Thanks!
