### ISSUE TITLE
Always use TypeScript parser

### ISSUE THREAD

**Issue by chancancode** [NullVoxPopuli/ember-eslint-parser#58]
Two options:

1. Always use `@typescript-eslint/parser`
   * Pros: less dependencies in this project
   * Cons: js-only apps may want to use Babel for the ability to use custom plugins
2. Add an option to choose which parser to use

Currently, we [conditionally choose](https://github.com/NullVoxPopuli/ember-eslint-parser/blob/57aeb861e4781c4047175c1a2283485be292cfcf/src/parser/gjs-gts-parser.js#L43) which parser to use per-file. This pushes a lot of complexity to the app, because you essentially need to configure two distinct parsers (e.g. installing the decorator babel plugin and passing it in `babelOptions`).

Essentially we are requiring users to manage [both of these branches](https://github.com/ember-cli/ember-cli/blob/fa8599058bde3c745a2b1156076955ca3543c857/blueprints/app/files/.eslintrc.js#L5-L15) simultaneously, which seems like a lot of busywork for ~no benefits.

I think it is generally not necessary and not a good idea to dynamically pick between one of these two parsers per-file, instead of having a fixed on per-project. You may end up getting subtly different behavior/error messages, plus it is just unnecessary overhead to need to learn both.

Personally, my preference would be to always default to using the TypeScript parser, but give users the option of opt-in to using babel if they require it:

```js
// ts/js project
{
  overrides: [
    {
      files: ['**/*.{js,ts,gjs,gts}'],
      plugins: ['ember'],
      // uses TypeScript parser, nothing to configure, just works
      parser: 'ember-eslint-parser'
    },
  ],
}
```

```js
// js only project
{
  overrides: [
    {
      files: ['**/*.{js,gjs}'],
      plugins: ['ember'],
      // still uses TypeScript parser internally, nothing to configure, just works, you probably won't ever notice
      parser: 'ember-eslint-parser'
    },
  ],
}
```

```js
// js only project that prefer/requires babel for some reason
{
  overrides: [
    {
      files: ['**/*.{js,gjs}'],
      plugins: ['ember'],
      parser: 'ember-eslint-parser',
      parserOption: {
        useBabel: true,
        sourceType: 'module',
        requireConfigFile: false,
        babelOptions: {
          plugins: [
            '@babel/plugin-proposal-do-expressions',
            ['@babel/plugin-proposal-decorators', { decoratorsBeforeExport: true }],
          ],
        },
      }
    },
  ],
}
```

**Comment by NullVoxPopuli** [comment]
Landed in 0.3.7, thanks for the suggestion!
